export const ENV_CONSTANTS = {
  DB_URI: 'DB_URI',
  DB_NAME: 'DB_NAME',
  JWT_SECRET: 'JWT_SECRET',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  REDIS_PASS: 'REDIS_PASS',
  PORT: 'PORT',
  ENV: 'ENV',
  SMTP_URL: 'SMTP_URL',
  EMAIL_FROM: 'EMAIL_FROM',
};
