export const SITE_CONFIG = {
  ADMIN_MAILING_LIST: 'admin_mailing_list',
  MAX_DEVICE_PER_USER: 'MAX_DEVICE_PER_USER',
  MAX_GEO_FENCE_PER_DEVICE: 'MAX_GEO_FENCE_PER_DEVICE',
  SUPPORT_MAILING_LIST: 'SUPPORT_MAILING_LIST',
  SOCIAL_LOGIN_ENABLED: 'SOCIAL_LOGIN_ENABLED',
  IS_USER_SITE_UNDER_MAINTENANCE: 'IS_USER_SITE_UNDER_MAINTENANCE',
  SITE_MAINTENANCE_MESSAGE: 'SITE_MAINTENANCE_MESSAGE',
  BLACKLISTED_EMAILS: 'BLACKLISTED_EMAILS',
};
